services :
  # Flutter web frontend service
  frontend:

    build:
      context: .
      dockerfile: Dockerfile
    container_name: fd-toolkit
    ports:
      - 8090:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro